export const MCHAT_QUESTIONS = [
    { id: 1, text: "Nếu bạn chỉ vào một điểm trong phòng, con bạn có nhìn theo không?", example: "VÍ DỤ, nếu bạn chỉ vào đồ chơi hay con vật, con bạn có nhìn vào đồ chơi đó hay con vật đó không?", reverse: false },
    { id: 2, text: "Bạn có bao giờ tự hỏi liệu con bạn có bị điếc không?", example: "", reverse: true },
    { id: 3, text: "Con bạn có chơi trò chơi tưởng tượng hoặc giả vờ không?", example: "VÍ DỤ, giả vờ uống nước từ một cái cốc rỗng, giả vờ nói chuyện điện thoại...", reverse: false },
    { id: 4, text: "Con bạn có thích leo trèo lên đồ vật không?", example: "VÍ DỤ, trèo lên đồ đạc trong nhà, đồ chơi ngoài trời, hoặc leo cầu thang", reverse: false },
    { id: 5, text: "Con bạn có làm các chuyển động ngón tay một cách bất thường đến gần mắt của bé không?", example: "VÍ DỤ, con bạn có vẫy/ đưa qua đưa lại ngón tay gần mắt của bé", reverse: true },
    { id: 6, text: "Con bạn có dùng ngón tay trỏ của bé để yêu cầu việc gì đó, hoặc để muốn được giúp đỡ không?", example: "VÍ DỤ, chỉ vào bim bim hoặc đồ chơi ngoài tầm với", reverse: false },
    { id: 7, text: "Con bạn có dùng một ngón tay để chỉ cho bạn thứ gì đó thú vị mà trẻ thích thú không?", example: "VÍ DỤ, chỉ vào máy bay trên bầu trời hoặc 1 cái xe tải lớn trên đường", reverse: false },
    { id: 8, text: "Con bạn có thích chơi với những đứa trẻ khác không?", example: "VÍ DỤ, con bạn có quan sát những đứa trẻ khác, cười với những trẻ này hoặc tới chơi với chúng không", reverse: false },
    { id: 9, text: "Con bạn có khoe bạn những đồ vật bằng cách mang hay ôm chúng đến cho bạn xem - không phải để được bạn giúp đỡ, chỉ để chia sẻ với bạn không?", example: "VÍ DỤ, khoe với bạn 1 bông hoa, thú giả, hoặc 1 cái xe tải đồ chơi", reverse: false },
    { id: 10, text: "Con bạn có đáp lại khi được gọi tên không?", example: "VÍ DỤ, con bạn có ngước tìm người gọi, nói chuyện, hay bập bẹ, hoặc ngừng việc bé đang làm khi bạn gọi tên của bé?", reverse: false },
    { id: 11, text: "Khi bạn cười với con bạn, con bạn có cười lại với bạn không?", example: "", reverse: false },
    { id: 12, text: "Con bạn có cảm thấy khó chịu bởi những tiếng ồn xung quanh?", example: "VÍ DỤ, con bạn có hét lên hay khóc khi nghe tiếng ồn của máy hút bụi, hoặc nhạc to?", reverse: true },
    { id: 13, text: "Con bạn của bạn có đi bộ không?", example: "", reverse: false },
    { id: 14, text: "Con bạn có nhìn vào mắt bạn khi bạn đang nói chuyện với bé, chơi cùng bé hoặc mặc quần áo cho bé không?", example: "", reverse: false },
    { id: 15, text: "Con bạn có bắt chước những điều bạn làm không?", example: "VÍ DỤ, vẫy tay bye bye, vỗ tay, hoặc tạo ra những âm thanh vui vẻ khi bạn làm", reverse: false },
    { id: 16, text: "Nếu bạn quay đầu để nhìn gì đó, con bạn có nhìn xung quanh để xem bạn đang nhìn cái gì không?", example: "", reverse: false },
    { id: 17, text: "Con bạn có cố gắng gây sự chú ý để bạn phải nhìn vào bé không?", example: "VÍ DỤ, con bạn có nhìn bạn để được bạn khen ngợi, hoặc nói 'nhìn' hoặc 'nhìn con'?", reverse: false },
    { id: 18, text: "Con bạn của bạn có hiểu bạn nói gì khi bạn yêu cầu con làm không?", example: "VÍ DỤ, Nếu bạn không chỉ tay, con bạn có hiểu 'để sách lên ghế' hoặc 'đưa mẹ/bố cái chăn' không?", reverse: false },
    { id: 19, text: "Nếu có điều gì mới lạ, con bạn có nhìn bạn để xem bạn cảm thấy thế nào về việc xảy ra không?", example: "VÍ DỤ, nếu con bạn nghe thấy 1 âm thanh lạ hoặc thú vị, hoặc nhìn thấy đồ chơi mới, con bạn có nhìn bạn không?", reverse: false },
    { id: 20, text: "Con bạn có thích những hoạt động mang tính chất chuyển động không?", example: "VÍ DỤ, được lắc lư hoặc nâng lên hạ xuống trên đầu gối của bạn không?", reverse: false },
  ];